CodableToTypeScriptをアップグレードして、TypeScriptASTによるコード生成に書き換える
sidepelican/CallableKit pull request #12
Opened 2022-11-26 02:02 UTC by omochi

https://github.com/omochi/CodableToTypeScript/pull/34

メモ

kind enum
any + simple upcast
block stmt
word "ident"

2022-11-26 03:15 UTC, omochi commented on Package.swift
> -        .package(url: "https://github.com/omochi/SwiftTypeReader", from: "2.0.0"),
こっち要らなそうだったので消しました。

2022-11-26 03:15 UTC, omochi commented on Package.swift
> -                "SwiftTypeReader",
こっちも要らないようです。

2022-11-26 03:15 UTC, omochi commented on Sources/Codegen/GenerateTSClient.swift
> -}
`ImportMap` は不要になりました。

2022-11-26 03:15 UTC, omochi commented on Sources/Codegen/GenerateTSClient.swift
> -
TypeScriptソースが公開しているシンボルをスキャンするので、
このような事前のテーブル定義も不要です。

2022-11-26 03:15 UTC, omochi commented on Sources/Codegen/GenerateTSClient.swift
> +        ])
自動で名前を収集するために、
文字列ではなくASTで構成する必要があります。

2022-11-26 03:15 UTC, omochi commented on Sources/Codegen/GenerateTSClient.swift
> +                body: TSBlockStmt(try stype.functions.map { (f) in
ここ以下の変更は、APIの変化に追従しているだけで、同じASTを組み立てています。

`TSIdentType.void` など、いくつかの名前は事前定義したので、文字列リテラルの利用が減っています。

2022-11-26 03:15 UTC, omochi commented on Sources/Codegen/GenerateTSClient.swift
> +                        args: [TSIdentExpr("raw")]
ここまでの変更は、APIの変化に追従しているだけです。

2022-11-26 03:15 UTC, omochi commented on Sources/Codegen/GenerateTSClient.swift
> +    ) throws -> TSSourceFile? {
解析するため文字列ではなくASTを構成します。

2022-11-26 03:15 UTC, omochi commented on Sources/Codegen/GenerateTSClient.swift
> +        return TSSourceFile(codes)
Import文の生成は、複数のソースコードを集めてから行うため、
この時点ではimportの無いコードを生成します。

2022-11-26 03:15 UTC, omochi commented on Sources/Codegen/GenerateTSClient.swift
> +    private func fixImport(decl: TSImportDecl) {
import文を直す関数を切り出しました。

2022-11-26 03:15 UTC, omochi commented on Sources/Codegen/GenerateTSClient.swift
> +            // generate all ts codes
commonとdecodeも含めて、全ての生成ソースを集めます。

2022-11-26 03:15 UTC, omochi commented on Sources/Codegen/GenerateTSClient.swift
> +            var symbolTable = SymbolTable()
デフォルト引数で、標準ライブラリのシンボルは事前登録されています。
もし、解析対象に無いTypeScriptライブラリがある場合 (npmから取ってくるものなど)、
ここでそのライブラリのシンボルを登録しておきます。

2022-11-26 03:15 UTC, omochi commented on Sources/Codegen/GenerateTSClient.swift
> +                for symbol in source.source.memberDeclaredNames {
`TSSourceFile.memberDeclaredNames` で、そのソースのトップレベルシンボルを集めます。

2022-11-26 03:15 UTC, omochi commented on Sources/Codegen/GenerateTSClient.swift
> +                    symbolTable.add(symbol: symbol, file: .file(source.file))
本当は一発で登録できる `symbolTable.add(source: source, file: file)` というのもあるんですが、
TypeScriptAST側で重複シンボルの処理が実装されていないため、
ここでは自分でループして一個ずつ登録するように書いています。

2022-11-26 03:15 UTC, omochi commented on Sources/Codegen/GenerateTSClient.swift
> +                let imports = try source.source.buildAutoImportDecls(symbolTable: symbolTable)
symbolTableが完成したら、 `TSSourceFile.buildAutoImportDecls` で、必要なインポート文の配列を生成できます。
いくつか細かい仕様があります。
既にimport文が含まれている場合、それも含めた結果を返します。
なにかの都合で自動対応しきれない場合は、import文を事前に入れておくことでなんとかできるようにしています。

第２引数の `defaultFile` を指定すると、
見つからなかったものは全部そこからimportしようとします。
従来のCodeGeneratorの `import { X } from ".."` を生成する挙動はこれによって再現されます。
ここでは指定していないので、その挙動は無効になっていて、
見つからなかった場合は例外を投げます。

2022-11-26 03:15 UTC, omochi commented on Sources/Codegen/GenerateTSClient.swift
> +                source.source.replaceImportDecls(imports)
`replaceImportDecls` で、既存のimport文を削除して、ファイル先頭にimport文を追加します。
これをもって自動インポート処理が完成します。

2022-11-26 03:15 UTC, omochi commented on Sources/Codegen/GenerateTSClient.swift
> +            for source in sources {
自動インポート処理されたすべての生成ファイルを、
`print()` APIによって文字列化して、実際にファイルに出力します。

2022-11-26 03:15 UTC, omochi commented on Sources/Codegen/GenerateTSClient.swift
> -
このへんは不要になりました。

2022-11-26 03:15 UTC, omochi commented on example/TSClient/src/Gen/common.gen.ts
> +}
少しスタイルの変化が生じました。

2022-11-28 02:57 UTC, sidepelican requested changes
ImportMapまわりのごちゃごちゃした部分がなくなって良くなったと思います。ありがとうございます。
互換性も良さそうでした。

Package.swiftの変更は`SwiftTypeReader`への依存は明示的にするべきだと思うので残したいです。

2022-11-28 02:57 UTC, sidepelican commented on Sources/Codegen/GenerateTSClient.swift
> +struct SourceEntry {
パッケージ全体で共有される名前なので、`TSSourceEntry`にするか`fileprivate`にしたいです。
この変更はTS部分のコード生成が主ですが、CallableKit全体ではSwiftコード生成部分も多いのでそことの区別を意識したいです。

2022-11-28 02:57 UTC, sidepelican commented on Package.swift
> -        .package(url: "https://github.com/omochi/SwiftTypeReader", from: "2.0.0"),
意味はあって、Swift向けコードの生成において`SwiftTypeReader`の機能の依存バージョンを明示するために必要になります。
C2TSがSwiftTypeReaderの最新に追従してないけど、SwiftTypeReaderの最新機能を使いたい、などの場合に必要になります。

2022-11-28 02:57 UTC, sidepelican commented on Sources/Codegen/GenerateTSClient.swift
> +struct SourceEntry {
```suggestion
fileprivate struct SourceEntry {
```

2022-11-28 02:57 UTC, sidepelican commented on Package.swift
> -                "SwiftTypeReader",
これも、`Codegen`がその実装で`SwiftTypeReader`を直接使って強く依存しているので書いてました。
例えば将来`CodableToTypeScript`が`SwiftTypeReader`に依存しなくなった場合に変なことになります。

2022-11-28 07:43 UTC, omochi commented on Package.swift
> -        .package(url: "https://github.com/omochi/SwiftTypeReader", from: "2.0.0"),
ああ、そうでしたね。SWTRだけをアップデートする場合もありえるのか。

2022-11-28 07:46 UTC, omochi commented on Package.swift
> -                "SwiftTypeReader",
なるほど。修正しました。

2022-11-28 07:47 UTC, omochi commented on Sources/Codegen/GenerateTSClient.swift
> +struct SourceEntry {
fileprivateつけました

2022-11-28 07:48 UTC, omochi commented on Sources/Codegen/GenerateTSClient.swift
> +struct SourceEntry {
たしかに。Swiftコードの生成部分も多く含まれるパッケージであるを意識していませんでした。

2022-11-28 07:49 UTC, omochi commented
指摘事項を修正しました。

2022-11-28 07:57 UTC, sidepelican approved these changes
良さそうです。対応ありがとうございます

2022-11-28 07:58 UTC, merged