TypeAliasのサポート
sidepelican/CallableKit pull request #23
Opened 2022-12-18 08:41 UTC by omochi

C2TSのTypeAliasサポートに追従します。

2022-12-18 08:43 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> +            try stype.walkTypeDecls { (stype) in
(SWTRではなく)C2TSで追加している `TypeDecl.walk` ですが、
Declは構造上さまざまなノードを子に持っているので、
動作に対して名前が一般的すぎるので変更しました。

型宣言だけに限って巡回するメソッドとして、適切な名前にしました。

2022-12-18 08:44 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> +                        || stype is TypeAliasDecl
`TypeAliasDecl` の変換を許可します。
また、このguardフィルターはネストされた宣言にも適用すべきに思えたので、
`walkTypeDecls` の内側に移しました。

2022-12-18 08:46 UTC, omochi commented on example/Sources/Client/Gen/FoundationHTTPStubClient.gen.swift
> +        try await withTaskCancellationHandler(operation: {
何もしてないのに壊れた！

2022-12-18 09:46 UTC, omochi commented on example/Sources/Client/Gen/FoundationHTTPStubClient.gen.swift
> +        try await withTaskCancellationHandler(operation: {
#24 で修正しました。

2022-12-18 16:36 UTC, sidepelican requested changes
どんどん進化してますね。ありがとうございます。
細かい点ですが気になった部分があるので対応お願いします

2022-12-18 16:36 UTC, sidepelican commented on Sources/CallableKit/GenerateTSClient.swift
> +                    return false
元々からあった問題ですが、namespaceとしてのclassが存在した場合にそのclassにぶら下がった型が見えなくなってしまうため、ここは`return true`であるべきように思いました

```swift
class UserModel {
  typealias ID = XXX
}
```

このような`UserModel.ID`が無視されるように思います

2022-12-18 16:36 UTC, sidepelican commented on Sources/CallableKit/GenerateTSClient.swift
> +                        || stype is TypeAliasDecl
> ネストされた宣言にも適用すべき

確かにそうですね。ありがとうございます

2022-12-18 16:36 UTC, sidepelican commented on example/TSClient/src/index.ts
> +    const res = await echoClient.testTypeAliasToRawRepr(student);
テスト的な意味合いではあんまり意味はないかもしれませんが、Swiftクライアント側にも同様のサンプルを追加してほしいです。

2022-12-19 06:39 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> +                    return false
たしかに。直しました。

2022-12-19 06:57 UTC, omochi commented on example/TSClient/src/index.ts
> +    const res = await echoClient.testTypeAliasToRawRepr(student);
`index.ts` と対応した内容が `Client/Main.swift` に書いてあったんですね。
追加しました。

2022-12-19 06:58 UTC, omochi commented
指摘事項に対応しました。

2022-12-19 10:46 UTC, sidepelican approved these changes
ありがとうございます。よさそうです

2022-12-19 10:47 UTC, merged