TSClientの生成にC2TSのPackageGeneratorを使う
sidepelican/CallableKit pull request #26
Opened 2023-01-05 13:04 UTC by omochi

#25 の実装

作業中

- [x] PackageGenerator を使う制御フローを実装する
- [x] CallableKit特有の生成を差し込む
- [x] サーバーとクライアントのSwiftの生成が壊れていないか確認する
- [x] 説明と気がついたことを書く

---

# 更新内容について

C2TSを新しくしたので、正確な型タグが導入されました。
作業していて、TypeScriptの型推論が悲鳴を上げまくっていたので、
https://github.com/omochi/CodableToTypeScript/pull/68#issuecomment-1368378803

実用性があるのか生成されたライブラリを使ってコードを書いてみる必要を感じています。
もしかしたら、型推論エラーが出まくって厳しいかもしれません。
一応、関数呼び出し時の型パラメータの明示や、式の分割でC2TSのテストケースの範囲では対応できました。

2023-01-07 08:10 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> +        ]
C2TSの `common.ts` はシステム設計の分離を良くするため、
そのまま使うようにしたので、
`Date` 系のカスタム関数は CallableKit のライブラリの方に含めます。

2023-01-07 08:11 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> +        var insertionIndex: Int = ts.source.elements.lastIndex(where: { $0 is TSImportDecl }) ?? 0
従来どおりの生成結果になるように、
import文の後ろに サービスプロトコルと具象クライアントを生成するようにします。

2023-01-07 08:11 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> -                codes += try converter.ownDecls().decls
このへんの型からの生成はC2TSに任せます。

2023-01-07 08:13 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> -        g.isOutputFileName = { $0.hasSuffix(".gen.ts") }
`Gen` 以下は全て自動生成物という規則があれば、拡張子による区別は不要だと思います。
そうすれば、 `Gen` を手で削除してもリスクが無いので扱いやすいと思います。
またその考えのもとで、C2TSでは `.gen.ts` ではなく `.ts` を生成します。

もしそうではない場合、手動生成物が混ざっているという事になりますが、
その場合は `Gen` の掃除がしにくいので良くないと思います。

2023-01-07 08:14 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> +                source: generateCommon()
CallableKitが導入する共通ライブラリです

2023-01-07 08:14 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> +            symbols.add(source: commonLib.source, file: commonLib.file)
import解決できるように登録しておきます。

2023-01-07 08:14 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> +                importFileExtension: .js,
`esnext` の場合はここを `.js` に設定します。

2023-01-07 08:14 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> +                try self.processFile(
ここでサービス関連の生成をフックします。

2023-01-07 08:15 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> +                print("generated...", file.relativePath)
ここにはC2TSが変更チェックした結果、実際に書き込んだ時だけ呼ばれます。
従来のメッセージの表示と同じタイミングになるので、ここにprintを置きました。

2023-01-07 08:16 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> +            modules.removeAll { $0 === input.context.swiftModule }
生成対象のモジュールリストを作ります。
読み込まれてるモジュールからSwift標準ライブラリを除去します。

2023-01-07 08:16 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> +            entries.append(commonLib)
`package.generate` が C2TS の生成結果を全て返します。
この時点では副作用はありません。
ここで CallableKit ライブラリを生成結果に追加しておきます。

2023-01-07 08:17 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> +                write.files.insert(file.relativePath)
全ての生成結果を `write` に登録して、この後の削除処理から保護します。
`URL.relativePath(from:)` は C2TS が public に提供している extension です。

2023-01-07 08:20 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> +            try package.write(entries: entries)
ここで実際にファイルシステムに対して副作用が生じます。
変更チェックを通った場合に `didWrite` を呼びます。

2023-01-07 08:20 UTC, omochi commented on Sources/CallableKit/Generator.swift
> +        .read(directory: srcDirectory)
APIが変わりました。

2023-01-07 08:21 UTC, omochi commented on Sources/CallableKit/Generator.swift
> +                    !isDir.boolValue
削除処理を分割して、ファイルを削除してから、空のディレクトリを削除するようにしました。
元々の実装では、ディレクトリを `sink.files` に登録するタイミングが無いので、
ディレクトリが意図せず削除されてしまったからです。

2023-01-07 08:23 UTC, omochi commented on Sources/CallableKit/Generator.swift
>              if !sink.files.contains(dstFile) {
ここなんですが、`sink.files` がフルパスではなく部分パスの `String` だったので取り扱いが難しかったです。
実際のファイルシステムのエントリを扱っている部分なので、`URL` で扱ってフルパスで扱うのはどうでしょうか？
そうすると利用側で書いている `relative(from:)` が不要になって少しシンプルにできます。

なお `URL` は内部表現として絶対パスと相対パス(+ベースパス)の2種類のモードがありますが、
後者の場合も `.path` でアクセスした場合はベースパスが合成されてフルパスになるので、
表面的にはフルパスを扱う型です。

2023-01-07 08:27 UTC, omochi commented on example/TSClient/src/index.ts
> +    const id = { rawValue: "id" } as User_ID;
`RawRepresentable` をトランスパイルした型のentity表現を、
Swiftのstructに合わせた表現に変更しました。
その方がSwiftの意味論に近い事もありますが、
新しいタグシステムと多重化されたRawRepresentableの組み合わせが正しく動くようにするには
こうする必要がありました。
もちろんJSON表現の方はRawValueのJSON表現のエイリアスになっているので、
他の型と同様、デコード関数を通してSwiftのCodableと通信できます。

2023-01-07 08:42 UTC, omochi commented
@sidepelican レビューお願いします

2023-01-07 14:38 UTC, sidepelican requested changes
対応ありがとうございます。TS生成まわりの難しい手続きが減って良くなったと思います。
細かい仕様変更部分は問題ないと思います。

いくつかコメントを書きましたが、
nextjsの部分とGenerator.OutputSinkを何とか使えないかの点が特に気になりました。

2023-01-07 14:38 UTC, sidepelican commented on Sources/CallableKit/GenerateTSClient.swift
> -        g.isOutputFileName = { $0.hasSuffix(".gen.ts") }
ここはちょっと悩ましいですね。
「`Gen`以下は全て自動生成物」という規則はそうなのですが、「全ての生成物はCallableKitによるもの」ではないのが問題となります。

既存プロジェクトではmockoloやneedleによる生成物も混ざった状態になっていて、CallableKitによる生成物かどうかを区別するために`.gen.swift`という拡張子を使用していました。
もちろん`.gen.swift`というsuffixを持っていたからといってCallableKitによる生成物であるとは約束されないので、場当たり的な仕様ではあります。

----

と書きはしましたが、元々の仕様が場当たり的であるのと単にディレクトリをもう1個深く掘れば解決するのでこの仕様でもいいと思いました

2023-01-07 14:38 UTC, sidepelican commented on Sources/CallableKit/GenerateTSClient.swift
> +                importFileExtension: .js,
元の仕様と同じように、`nextjs` フラグがONのときは拡張子を無しにするようにしてほしいです。
これはNext.jsが変な仕様を持ってて、`.js`の拡張子をうまく解釈してくれないためです。（参照: https://github.com/sidepelican/CallableKit/pull/6 ）

また、ここの変更によって `func fixImport` は不要になってると思うので削除をお願いします

2023-01-07 14:38 UTC, sidepelican commented on Sources/CallableKit/GenerateTSClient.swift
> +                print("generated...", file.relativePath)
このprint文はおまけでしたが、細かいところまで再現ありがとうございます。

2023-01-07 14:38 UTC, sidepelican commented on Sources/CallableKit/GenerateTSClient.swift
> +                write.files.insert(file.relativePath)
書き込み処理がC2TS側で行われることになったので `Generator.OutputSink` がハッキーな使い方をされる形になってしまいましたね。
Swiftサイドのコード生成には `Generator.OutputSink` の仕組みがそのまま動いてるので、書き込み処理が統一されていないのは生成時の振る舞いがブレる可能性があって好ましくないですね。

`entries` の状態から `Generator.OutputSink` を使って書き込みを行うことは難しいでしょうか？

2023-01-07 14:38 UTC, sidepelican commented on Sources/CallableKit/Generator.swift
>              if !sink.files.contains(dstFile) {
いやーそうなんですよね。同じ相対パスでも `./`から始まるか否かで変わったりもして、使いづらいと思ってました。
相対パスをうまく扱うユーティリティがなくて面倒くさがって放置していました。

なんでこうなってるのか覚えてないですが、フルパスで扱うのもいいと思います。

2023-01-07 14:38 UTC, sidepelican commented on Sources/CallableKit/Generator.swift
> +                    !isDir.boolValue
ディレクトリを削除してしまわないように `func findFiles` が用意されてるんですが、何かの拍子に使われなくなってますね・・・

2023-01-07 14:38 UTC, sidepelican commented on example/TSClient/src/index.ts
> +    const id = { rawValue: "id" } as User_ID;
あ〜RawRepresentableってTSでも`rawValue`にラップされるんですね。

Swiftの再現度が高いのは良いですが、`string & TagRecord<"User_ID">` のほうが嬉しいです。
一番問題だと思うのは `console.log(userID)` したら `[object Object]` が出る点で、変なバグを埋め込みやすいと思うんですよね。
他生成がめんどくさいのも気になります。

文字列化は`toString()` とかも実装すれば大丈夫そう、生成はユーティリティ関数も用意すれば何とかなるとは思うのですが、気持ち的に `string`や`number`として取り扱ってる面が強いタイプの型だと思うので、他に変なケースが出てこないか気になります。`fooID === barID` が直感的に動かない点など。

タグシステムはこの形対応できないんでしたっけ。できてたつもりでいたのであとで確認します。

とりあえずこのPRとは直接関係ないのでここは修正しなくても大丈夫です。

2023-01-07 16:43 UTC, sidepelican commented
余談なんですが、このコード生成器の初期の設計思想として入力ファイル数がメモリ消費量が増えないように、生成コードはメモリ上に同時に1つしか存在しないようになっていました。
`OutputSink.callAsFunction`がその場で書き込みを行って入力は即座に捨てる挙動も、この設計思想がもとになっています。

現実的にはメモリが足りなくなることはないだろうので重視はしてないですが、import自動解決処理も旧来の処理のように2パスでスキャンとコード生成を分けれるとASTのメモリ使用量が減って面白いかもしれませんね

2023-01-08 04:32 UTC, omochi commented on Sources/CallableKit/Generator.swift
>              if !sink.files.contains(dstFile) {
またの機会に修正を投げますね。

2023-01-08 04:33 UTC, omochi commented on Sources/CallableKit/Generator.swift
> +                    !isDir.boolValue
なるほど。`findFiles` を使う形に直します。

2023-01-08 04:40 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> -        g.isOutputFileName = { $0.hasSuffix(".gen.ts") }
なるほど。

> `.gen.swift` というsuffixを持っていたからといってCallableKitによる生成物であるとは約束されない

そのとおりですが一定の利便性として納得しました。
`.gen.ts` だと他のツールの生成物と衝突することもありそうですが、
例えば `.c2.ts` にすれば実用的には衝突を回避できそうです。

C2TSとして生成物の拡張子をカスタムできるようにしようと思います。
設計的な負荷もないので。

2023-01-08 04:41 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> +                importFileExtension: .js,
ああ、既存の機能を見落としていました。
対応します。

2023-01-08 04:42 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> +                print("generated...", file.relativePath)
開発中は設定ミスなどで実行が空振りになったりするので、
こういうユーザー向けのメッセージはツールの使いやすさとして重要だと思ってます。

2023-01-08 05:00 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> +                write.files.insert(file.relativePath)
`PackageGenerator.write(entries:)` を使わなくとも、
`PackageEntry` の内容だけで生成されるコードの内容が確定するようにはなっているので、
そのように書き換える事は可能です。

ただ、元々のCallableKitの挙動だと、内容の変更が無くても再出力を行います。

C2TSは内容を一度読んで出力を防ぎます。
こうすると余計なタイムスタンプの更新が防止できて、
もし後段のシステムにタイムスタンプベースのキャッシュ管理がある場合には都合が良いからです。

このような改善ができるので PackageGenerator.write を使うように書きましたが、
確かにややこしくなってしまいました。

とはいえ同一内容の出力防止については、必要なら `Generator.OutputSink` が実装すれば良いので、
`OutputSink` を使うように変更します。

2023-01-08 06:02 UTC, omochi commented on example/TSClient/src/index.ts
> +    const id = { rawValue: "id" } as User_ID;
例えば以下のように2段のRawRepresentableを考えます。

```swift
struct ID: RawRepresentable { var rawValue: String }
struct UserID: ID { var rawValue: ID }
```

タグシステムは `型 = 表現型 & タグ` の形です。
そのため、それぞれ以下のようにトランスパイルされます。

```ts
type ID = string & TagRecord<"ID">
type UserID = ID & TagRecord<"UserID">
```

ここで、  `UserID` の右辺の `ID` を展開すると次のようになります。

```ts
type UserID = string & TagRecord<"ID"> & TagRecord<"UserID">
```

ここで `TagRecord<Name>` というのは、プロパティ `$tag` が `Name | undefined` という定義ですから、
合成された結果は `$tag: ("ID" | undefined) & ("UserID" | undefined)` を意味しています。
これは変形して `$tag: ("ID" & "UserID") | undefined` と等価です。

しかし、 異なる2つの文字列を同時に満たす文字列というものは無いので、
`$tag: never | undefined` になってしまってタグが消えます。

<img width="245" alt="スクリーンショット 2023-01-08 14 42 07" src="https://user-images.githubusercontent.com/312792/211182287-6a638234-2b12-4702-be32-b90756a69020.png">

また、このような重なる合成は型パラメータがあるときにもおかしくなります。
`X<A, B>` と `Y<C, D>` が合成されると、 `[0]: A & B` と `[1]: C & D` になりますが、
順序性が失われているので、 `X<A, B> & Y<C, D>` と `X<C, D> & Y<A, B>` が区別できません。

現状実装の理屈レベルで言えばこういう話なんですが、
やろうとしていることが、
Swiftでstructの継承をしようとしているのと同じと考えると、
そもそも要求が不自然だったのかなと思います。

> 文字列化はtoString() とかも実装すれば大丈夫そう

`class` ではなく `type` なので、共通の実装を提供できないのでこの手は使えないですね。
`init` も提供して `{ rawValue: "ABCD" }` の代わりに `ID_init("ABCD")` と書くようにした上で、
内部では `class` を `new` して返すという手はあるけど、
実体を手で作るパターンが残るのも微妙ですねえ。

> fooID === barID が直感的に動かない点など。

これはまあそうですが、RawRepresentable以外の Equatable な structも、
TypeScriptに持っていくと全部ここがidentity equalになってしまう問題はあるので、
いずれにしても気をつける必要がある部分であって、
RawRepresentableだけ特別対応してサポートするのは逆にわかりにくい気がします。

2023-01-08 07:33 UTC, sidepelican commented on example/TSClient/src/index.ts
> +    const id = { rawValue: "id" } as User_ID;
なるほど、多重化RawRepresentableがどういうことか分かりました。たしかにこれは対応できないですね。

`toString()` に関しては、decode時に`toString()`関数をオブジェクトに埋め込む想定でいました。classを作るのでも同じですね。あんまりいけてないとは思います。

> RawRepresentable以外の Equatable な structも、TypeScriptに持っていくと全部ここがidentity equalになってしまう

確かにここを諦めてる前提があるので同様に諦めるほうが統一感ありますね。
C2TSは汎用的かつなるべくSwiftを忠実に再現することを目指すべきだと思うので、この仕様でも良いと思いました。

ただやっぱり現実問題としてTSでは `{ rawValue: T }` の誤用を型では防げない点が気になります。
思えば値をラップしてファントムタイプを実現するのはSwiftの高度な機能に頼ってる部分が強かったんですね。

`{ rawValue: T }` になるくらいなら初期のように`string`につぶれていたほうが嬉しいため、CallableKit独自で何かしら対応はしたい（あるいは既存の`ID`suffixを自動でstringに変換するルールに積極的に乗っかる）とは思います。

2023-01-08 09:04 UTC, omochi commented on example/TSClient/src/index.ts
> +    const id = { rawValue: "id" } as User_ID;
> toString() に関しては、decode時にtoString()関数をオブジェクトに埋め込む想定でいました。classを作るのでも同じですね。あんまりいけてないとは思います。

decode時の場合はそれでもよくて、問題は `type` 式に基づいて手書きリテラルでコンストラクトできる穴が残るところですね。そのためのケースとしてinitも提供する案を書きましたが、それを使い忘れる可能性が残ります。
そもそもtypeではなくclassにトランスパイルするという方法なら、
toStringに関しては穴がふさがりますが、`==` の不便さ？は残るのと、
TypeScriptだとtypeのほうが流行ってますよね。

> 確かにここを諦めてる前提があるので同様に諦めるほうが統一感ありますね。

はい、RawRepresentableは結局encode/decodeについての挙動、つまりJSON表現を提供しているだけであって、
Swiftでも元の型として扱うときは、 `.init(rawValue: string)` と `id.rawValue` を使う必要があるただのstructですね。
そもそもID的な利用方法はRawRepresentableの一部ですし。

> 値をラップしてファントムタイプを実現する

そうですね。Swiftで便利なのは、 `struct UserID { ... }`、 `struct StudentID { ... }` をそれぞれ作らなくても、
`struct GenericID<Phantom> { ... }` を作れば `GenericID<User>`, `GenericID<Student>` を構成できるところですね。
それと、Equatableによって `==` のセマンティクスを型ごとにコントロールできるところですね。
TypeScriptには値型のコンセプトがないので、オブジェクトは全て参照型になってしまうところが原因とも言えそうです。

> C2TSは汎用的かつなるべくSwiftを忠実に再現することを目指すべきだと思うので、この仕様でも良いと思いました。

C2TSとして複数の生成器を提供して、デフォルトの挙動は現状のラップ構造体としつつ、
TypeMapやTypeConverterProviderによって別の生成モードをユーザーが選択する、
というアーキテクチャはありえると思います。
ID suffixで string にするというのもその一つですね。

ただ旧実装の `string & tag` はジェネリックな場合にうまく動かないという問題があって、
いろいろ検討した結果最終的に正しい型タグに辿り着いた経緯です。

型タグがつかないstringで、ジェネリクス構造を無視して型名から生成するパターンであれば、
SwiftにおいてはRawRepresentableではなくTypeAliasですね。

```swift
// swift
typealias UserID = GenericID<User>
```

↑が↓になるなら・・・

```ts
// ts
type UserID = string;
```

```swift
// swift
typealias UserID = string;
```

↑これのトランスパイル結果がまさにそれと同じです。

現在の実装は、
型タグタグをつける + `GenericID<T>` を正しくTypeScript側にも存在させる、
ところが難しさに影響しています。
与えられた型パラメータを更にタグに織り込む必要があるためですね。

2023-01-08 09:14 UTC, omochi commented
> 余談なんですがこのコード生成器の初期の設計思想として、入力ファイル数が増えてもメモリ消費量が増えないように、生成コードはメモリ上に同時に1つしか存在しないようになっていました。

名前の定義と実際のコードの生成のフェーズを分けると、
今回のように `didGenerateEntry` でユーザーがコードを追加するようなパターンのために、
名前定義用とコード生成用の2つのAPIが生えて複雑になるのと、
その2つが正しく一貫性を持っていないとバグになりうるという点で、
生成コードをいったん全部作ってから一括でimport解決を行う構成にしています。

また、今はAST生成したコードに定義されたシンボル
（もしくは明示的にSymbolTableに書き込むか）しか解決できないのですが、
npmでインストールするライブラリのシンボルも解決できたらいいなと思っていて、
その場合は結局ライブラリのソースコードをパースする事になります。
要するにvscodeの挙動と同じですね。

なのでアーキテクチャとして自然なのはソースコードを読みとる作りだと思っていて、
現状はたまたまそれがASTしか読み取れないと捉えています。
パースはソースコードをASTに変換する処理なので。

生成されるシンボルだけ先に抽出するというのは面白いですが、
設計として汎用性が無いので過度な最適化だと感じます。

メモリ消費量に関しては、
もし問題になるならいったんASTをファイルシステムに書き出すのが良い方向だと思っています。

2023-01-09 13:44 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> -        g.isOutputFileName = { $0.hasSuffix(".gen.ts") }
`.gen.ts` で生成するようにしました。

2023-01-09 13:50 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> +                importFileExtension: .js,
`nextjs` のときは拡張子なし、そうでないときは `.js` の import文 を出すようにしました。

ちなみに、nextjsが変な仕様というわけではなさそうです。
`tsconfig.json` で `module` に `commonjs` を設定した場合には、
TypeScriptコンパイラは拡張子なしを期待するようです。

TypeScriptソースコードで `import { } from "a.ts"` というふうに、
わざと間違えて `.ts` を書くと、そのようなエラーメッセージが出ます。
`module` を `esnext` に変更した場合、エラーメッセージが変化して、 `.js` と書くように促されます。

2023-01-09 13:51 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> +                write.files.insert(file.relativePath)
`Generator.OutputSink` を使用するようにしました。

2023-01-09 13:53 UTC, omochi commented on Sources/CallableKit/Generator.swift
> +                    !isDir.boolValue
`findFiles` を使うように変更しました。

ところで、 `findFiles` 内部で `subpaths` が使用されてしましたが、
これはエラーをnilで返す古いAPIであり、
エラーを例外で返す `subpathsOfDirectory` が新しいAPIのようでしたので、
それを使うように変更しました。

2023-01-09 13:54 UTC, omochi commented
@sidepelican 指摘された点を修正しました。
指摘があったスレッドそれぞれに返信も書きました。

2023-01-09 16:49 UTC, sidepelican commented on Sources/CallableKit/GenerateTSClient.swift
> +                importFileExtension: .js,
そうでしょうか？
ユーザが期待するビルド構成に応じて変化するのはそうなんですが、かといってわざわざTSがサポートしている`.js`をサポートせず、TSがエラーを出す`.ts`を良しとするnextjsの挙動は、何らかの意図があるにせよ標準的ではないと感じます。
拡張子なしの場合は同じ挙動になってますね。

2023-01-09 17:06 UTC, sidepelican approved these changes
よさそうです。ありがとうございます。
TS側の型推論の問題とRawRepresentableについて後方互換性がないためそろそろバージョンを切ることにしました。
型推論がうまくいくかはサンプル以外のプロジェクトでもためしてみます。
RawRepresentableについてはオリジナルのコンバータを用意して選択できるようにするのは良さそうですね。

2023-01-09 17:06 UTC, merged

2023-01-09 22:42 UTC, omochi commented on Sources/CallableKit/GenerateTSClient.swift
> +                importFileExtension: .js,
ああ、誤解してました。
`.js` がimportできなくて `.ts` を要求する、typescript compilerにない挙動をするのはかなり変ですね。
どうやって実装しているんだろう・・・

ちなみにdenoでは `.ts` で import するらしいです。
https://deno-ja.vercel.app/manual/examples/import_export

とりあえずc2tsでは `.ts` での import文も対応しておこう。

2023-01-10 01:30 UTC, sidepelican commented on Sources/CallableKit/GenerateTSClient.swift
> +                importFileExtension: .js,
おお、Denoで`.ts`なのは初めて気づきました。
結構バラバラなんですね